### ISSUE TITLE
Save User at Admin Panel

### ISSUE THREAD

**Issue by gamefanpage** [mangopik/Sximo-Laravel#17]
An error appear when save user at config user panel
first i guess it was my file but also Your demo site has the same issue
when you want edit an user for like edit active or whatever then clic save button without put info inside box you'll get errors
http://demo.sximobuilder.com/v30/users/add/tta9y-iNxN

``` code
ErrorException
Undefined index: is_multiple
```

 /home1/kangopik/public_html/sximodemo/v30/protected/app/controllers/BaseController.php

line 458

``` code
    if($f['option']['is_multiple'] ==1)
```

**Comment by mangopik** [comment]
We notice this is a bug from ajax plugins distribution .  to solve the issue , we need to edit line code 458 to be 

``` php
if(isset($f['option']['is_multiple']) && $f['option']['is_multiple'] ==1)
```

**Comment by gamefanpage** [comment]
Ok thanks

**Comment by Jagy2014** [comment]
Nice, but now in file protected\app\library\SiteHelpers.php
Line 507

Should be changed to following:
if(isset($option['is_multiple']) && $option['is_multiple'] ==1)
