### ISSUE TITLE
Free extension can't be downloaded

### ISSUE THREAD

**Issue by gamefanpage** [mangopik/Sximo-Laravel#20]
I wrote it here as i think you don't read your website

http://mangopik.com/extension/show/jEq9y-LFQG

even if i have both license set on my panel i can't download some of them

can you please if it thanks :)

**Comment by mangopik** [comment]
Hi Mate , This extension already included at V30 .

**Comment by gamefanpage** [comment]
ah
nevermind i found why some can't download your file
http://sximobuilder.com/extension/mylicences
you have 2 places for set your licenses so i just find out that from here i had only one license set ><

mean your script read one this frontend panel instead the other one

and yeah i noticed it was already installed just right now lolll by doing the test
