### ISSUE TITLE
Ajax show error for element select

### ISSUE THREAD

**Issue by ZubikIT** [mangopik/Sximo-Laravel#25]

**Comment by mangopik** [comment]
Can you explain what error appear ?

**Comment by ZubikIT** [comment]
http://imgur.com/uHplKDX
If not show red line if selected not select

**Comment by gamefanpage** [comment]
you mean you can't select into the scroling box?

**Comment by ZubikIT** [comment]
I can selected, but not show error
http://imgur.com/64AGtNj

**Comment by gamefanpage** [comment]
ahhh yeah i see it and confirm about this bugs
when box is selected as Required it doesnt act like a required query and you can proceed to complete your form without entry from box

**Comment by ZubikIT** [comment]
how can I fix it?

**Comment by gamefanpage** [comment]
Need wait for mango :+1:

**Comment by dcurrito** [comment]
The problem is when you buid a select imput as required, the code in view form.blade.php generated is:
select name='name' rows='5' id='name' code='{$name}' 
                            class='select2 '  requred  ></select 
Notice the missing i in required.

**Comment by mangopik** [comment]
this issue equal with this [https://github.com/mangopik/Sximo-Laravel/issues/45](https://github.com/mangopik/Sximo-Laravel/issues/45)
