### ISSUE TITLE
For BaseController::getComboselect() add access right for entry_by selected.

### ISSUE THREAD

**Issue by ZubikIT** [mangopik/Sximo-Laravel#26]

**Comment by mangopik** [comment]
you can add this by create custom combo select .

**Comment by penny-this** [comment]
Example?

**Comment by mangopik** [comment]
edit your form and javascript codes 

``` php
$(document).ready(function() { 
    $("#field").jCombo("{{ URL::to('yourmodule/comboselect?filter=table:field:displayfield&limit=WHERE:entry_by:=:'.Session::get('uid'))}}",
    {  selected_value : '' });   
});
```

**Comment by ShehataGhattas** [comment]
Dear mangopik
if i need to add many limit condition like the below 

$("#test").jCombo("{!! url('test/comboselect?filter=pos:po_code:po_code&limit=WHERE:done_by:!=:1&limit=WHERE:entry_by:=:'.Session::get('uid')) !!}",

or how to change the 

	function getComboselect( Request $request)
	{

		if($request->ajax() == true && \Auth::check() == true)
		{
			$param = explode(':',$request->input('filter'));
			$parent = (!is_null($request->input('parent')) ? $request->input('parent') : null);
			$limit = (!is_null($request->input('limit')) ? $request->input('limit') : null);
			$rows = $this->model->getComboselect($param,$limit,$parent);
			$items = array();
		
			$fields = explode("|",$param[2]);
			
			foreach($rows as $row) 
			{
				$value = "";
				foreach($fields as $item=>$val)
				{
					if($val != "") $value .= $row->{$val}." ";
				}
				$items[] = array($row->{$param['1']} , $value); 	
	
			}
			
			return json_encode($items); 	
		} else {
			return json_encode(array('OMG'=>" Ops .. Cant access the page !"));
		}	
	}

to receive array from php link

$("#test").jCombo("{!! url('test/comboselect?filter=pos:po_code:po_code&limit[]=WHERE:done_by:!=:1&limit[]=WHERE:entry_by:=:'.Session::get('uid')) !!}",

it was only read the last condition  please advice
