### ISSUE TITLE
insert Inline Add row  ( ajax plugins )  

### ISSUE THREAD

**Issue by mangopik** [mangopik/Sximo-Laravel#3]
We will add inline add rows to all Generated modules .

**Comment by mangopik** [comment]
Replace files / protected/app/views/admin/module/template/ajax/table.php  with this patch http://sximobuilder.com/uploads/patch/table.zip

**Comment by ashishtechie83** [comment]
Will this make all inline rows in version 2.9 lcrud +ajax

**Comment by mangopik** [comment]
No Mate , just add quick save

**Comment by ZubikIT** [comment]
If I add to relationa then get error:
Next exception 'Illuminate\Database\QueryException' with message 'SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`penny`.`widgets`, CONSTRAINT `FK_widgets_wcategories` FOREIGN KEY (`wcid`) REFERENCES `wcategories` (`wcid`)) (SQL: insert into `widgets` (`description`, `products`) values (, ))' in D:\OpenServer\domains\localhost\github\penny2\vendor\laravel\framework\src\Illuminate\Database\Connection.php:625
Stack trace:

**Comment by mangopik** [comment]
You're right , sximo still dont have  InnoDB foreign key error handler . 

so make sure set foreign key **On Update** and **On Delete** are No Action

**Comment by ZubikIT** [comment]
Ok, thank you.

**Comment by ZubikIT** [comment]
May be remove or disable from template generate AJAX add insert inline if not working?
Or when you plan to make it to the end?

**Comment by Jagy2014** [comment]
How to add search button as it was in 2.9 ?
