### ISSUE TITLE
Set default languange is not working

### ISSUE THREAD

**Issue by mangopik** [mangopik/Sximo-Laravel#32]
when you set default languange , sistem still set English as default language

solution , add new session for lang at postSignin()

open file /protected/app/controllers/User.php

``` php

    Session::put('uid', $row->id);
    Session::put('gid', $row->group_id);
    Session::put('eid', $row->email);
    Session::put('ll', $row->last_login);
    Session::put('fid', $row->first_name.' '. $row->last_name); 
    /* revision code / additional code */
    if(!is_null(Input::get('language')))
    {
        Session::put('lang', Input::get('language'));   
    } else {
        Session::put('lang', 'en'); 
    }
    /* end revision code / additional code */
```

**Comment by gamefanpage** [comment]
Strange on my local when i worked on language i don't have any kind of issue even if i relog it stay with the language i set

but maybe it's because i edited many file ok it and i did more protected folder as a basic laravel installation folder

**Comment by alanjholiveira** [comment]
gamefanpage, the problem only appears when you define the configuration language, even choosing the default language the sximo still ingles.

**Comment by gamefanpage** [comment]
Well dunno if you checked my work that i made on translation at first time
but hey i did edit file by a lot since so i can't confirm u that my work is same as original now 
and i don't have issue as u said ><

**Comment by penny-this** [comment]
If authorized with social network not work set default langualge
