### ISSUE TITLE
TextArea automatically added <p></p>

### ISSUE THREAD

**Issue by shootsoft** [mangopik/Sximo-Laravel#33]
If you set a column type as the TextArea, when you add/edit a record, after click "Save" button, it will automatically add "&lt;p&gt;&lt;/p&gt;" around the text you just typed in

**Comment by gmmedia** [comment]
i hope that get fixed!

**Comment by mangopik** [comment]
open file /protected/app/controllers/BaseController.php

change line 408

``` php
if($f['type'] =='textarea_editor' || $f['type'] =='textarea')
{
    $content = (isset($_POST[$field]) ? $_POST[$field] : '');
    /* Use this filter for html sanity
    $data[$field] =  Purifier::clean($content);
    */
     $data[$field] = $content;
} 

```
