### ISSUE TITLE
Error table selection

### ISSUE THREAD

**Issue by shootsoft** [mangopik/Sximo-Laravel#34]
When you set a column as a Selection Option / Custiom Value
0 : a
1 : x
2 : y
3 : z

The list page will get an wrong selection drop down list like this:
1 : x
1 : x
1 : x
1 : x

repeat the second key and value

**Comment by mangopik** [comment]
Please check here [https://github.com/mangopik/Sximo-Laravel/issues/2](https://github.com/mangopik/Sximo-Laravel/issues/2)

**Comment by shootsoft** [comment]
Thanks~
It works.
