### ISSUE TITLE
Does Sximo-Laravel support this type of checkbox?

### ISSUE THREAD

**Issue by shootsoft** [mangopik/Sximo-Laravel#37]
For example
table1
id, name, selection
1, group1, 1,2
2, group2, 3

table2
id, item_name
1, item1
2, item2
3, item3

Expected view

table1 view

1, group1, ( item1, item2)
2, group2, ( item3)

when create new table1's record:

name: 
items: checkbox1=item1 checkbox2=item2 checkbox3=item3

**Comment by mangopik** [comment]
Not Yet mate . we will put this in the roadmap

**Comment by shootsoft** [comment]
Thanks~
