### ISSUE TITLE
How to update column's name

### ISSUE THREAD

**Issue by shootsoft** [mangopik/Sximo-Laravel#72]
I changed a column's name in MySQL manually. So how to update model's name? I tried to rebuild, but it doesn't work

**Comment by shootsoft** [comment]
I think this function is very important for iterative development. When I add new columns to a module, I have to backup controllers, views and models first, delete the old module, re-add module and modify new controllers, views and models.

**Comment by mangopik** [comment]
Please use forum for question or request
