### ISSUE TITLE
CNF_MODE missing in ConfigController.php

### ISSUE THREAD

**Issue by Jagy2014** [mangopik/Sximo-Laravel#77]
settings.php not updating when changing between development or production modes.

**Comment by mangopik** [comment]
what's your sximo version ?

**Comment by Jagy2014** [comment]
Sximo-laravel 3.1 + ajax modules. 

I found that ConfigController.php in AJAX modules missing this:
$val .=     "define('CNF_MODE','".(!is_null(Input::get('cnf_mode')) ? 'production' : 'development' )."');\n";

**Comment by Jagy2014** [comment]
Update ajax to 3.1!
Checked other files. There is more old things. Please check all ajax plugin files and update them to latest version.

**Comment by Jagy2014** [comment]
Please comment aswell

**Comment by mangopik** [comment]
are u using ajax latest ?

**Comment by Jagy2014** [comment]
yes, for v3

2015-07-17 12:15 GMT+03:00 Taufik Firmansyah notifications@github.com:
